variable "system" {}
variable "env" {}
variable "myip" {}
variable "instance_cnt" {}
variable "ami" {}
variable "type" {}
variable "key_name" {}
variable "vpc_cidr" {}
variable "cidr_public" {}
variable "cidr_private" {}